version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: decola_tech
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_prod
    ports:
      - "5432:5432"
    volumes:
      - avanade_data:/var/lib/postgresql/data

volumes:
  avanade_data: