spring:
  datasource:
    url: jdbc:h2:mem:sdw:2023
    username: sdw2023
    pssword:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | create | update | create-drop
    properties:
      hibernate:
        format_sql: true
    h2:
      console:
        enable: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false
